import AssistantDomain
import ExecutiveSupport
import Foundation

/// All demo content lives here.
///
/// Two rules keep it useful rather than misleading:
///
/// 1. It is built relative to "now", so the app always looks current instead of
///    drifting into the past.
/// 2. Reminder plans are **generated by the real planner** —
///    `DefaultSupportPlanner` — rather than hand-written. What the UI shows is
///    genuinely what the core would produce for these commitments.
///
/// None of this reaches a real user. Since persistence landed,
/// `AppLaunchConfiguration` only asks for seeding in a `DEBUG` build that was
/// launched with `-seed-demo-data`, and that launch runs against an in-memory
/// store rather than the user's database.
struct DemoData {
    let profile: UserProfile
    let settings: AssistantSettings
    let events: [CalendarItem]
    let tasks: [TaskItem]
    let memories: [MemoryItem]
    let reminderPlans: [ReminderPlan]

    /// Identifiers the seeded conversation refers to.
    let haircutEventID: CalendarItem.ID
    let gettingReadyMemoryID: MemoryItem.ID

    static func make(now: Date, calendar: Calendar) -> DemoData {
        let today = calendar.startOfDay(for: now)

        func at(_ day: Date, _ hour: Int, _ minute: Int = 0) -> Date {
            calendar.date(
                bySettingHour: hour,
                minute: minute,
                second: 0,
                of: day
            ) ?? day
        }

        func day(offset: Int) -> Date {
            calendar.date(byAdding: .day, value: offset, to: today) ?? today
        }

        /// The next Sunday strictly after today.
        func nextSunday() -> Date {
            let weekday = calendar.component(.weekday, from: today)
            let delta = (8 - weekday) % 7
            return day(offset: delta == 0 ? 7 : delta)
        }

        // MARK: Profile and settings

        let profile = UserProfile(
            displayName: "You",
            wakeTime: TimeOfDay(hour: 7),
            sleepTime: TimeOfDay(hour: 23, minute: 30),
            defaultPreparationDuration: TimeSpan.minutes(45),
            defaultTravelDuration: TimeSpan.minutes(30),
            quietHours: DayWindow(
                start: TimeOfDay(hour: 23),
                end: TimeOfDay(hour: 7)
            )
        )

        var settings = AssistantSettings()
        // Apple's on-device model is the intended default. It is not available
        // yet, and the UI says so rather than hiding it.
        settings.preferredProviderID = "apple.foundation-models"
        settings.routingPolicy = .preferOnDevice

        // MARK: Calendar

        let sunday = nextSunday()

        let workEvent = CalendarItem(
            title: "Work",
            start: at(today, 16),
            end: at(today, 22),
            location: "Work",
            importance: .high,
            travelDuration: TimeSpan.minutes(30),
            preparationDuration: TimeSpan.minutes(45)
        )

        let haircutEvent = CalendarItem(
            title: "Haircut",
            start: at(sunday, 22),
            end: at(sunday, 23),
            location: "Barber",
            importance: .normal,
            travelDuration: TimeSpan.minutes(30),
            preparationDuration: TimeSpan.minutes(45)
        )

        let dentistEvent = CalendarItem(
            title: "Dentist",
            start: at(day(offset: 9), 11),
            end: at(day(offset: 9), 11, 45),
            location: "Dental clinic",
            importance: .high,
            travelDuration: TimeSpan.minutes(20),
            preparationDuration: TimeSpan.minutes(20)
        )

        // MARK: Tasks

        let billTask = TaskItem(
            title: "Pay electricity bill",
            details: "The account number is in the email from last month.",
            status: .reminded,
            importance: .high,
            timing: .dueBy(at(today, 21)),
            deadline: at(today, 21),
            createdAt: at(day(offset: -2), 9, 12)
        )

        var tasks: [TaskItem] = [
            billTask,
            TaskItem(
                title: "Call the dentist",
                details: "Ask whether the appointment can move to the afternoon.",
                importance: .normal,
                timing: .flexible(
                    TimeWindow(start: now, end: at(day(offset: 5), 18))
                ),
                createdAt: at(day(offset: -1), 20, 4)
            ),
            TaskItem(
                title: "Finish the portfolio update",
                details: "Two case studies left to write up.",
                status: .inProgress,
                importance: .high,
                timing: .dueBy(at(day(offset: 3), 18)),
                deadline: at(day(offset: 3), 18),
                createdAt: at(day(offset: -6), 14, 30)
            ),
            TaskItem(
                title: "Renew the gym membership",
                status: .needsFollowUp,
                importance: .normal,
                timing: .dueBy(at(day(offset: 5), 20)),
                deadline: at(day(offset: 5), 20),
                followUpCount: 1,
                createdAt: at(day(offset: -4), 10)
            ),
            TaskItem(
                title: "Water the plants",
                status: .snoozed,
                importance: .low,
                timing: .fixed(at(today, 19, 30)),
                snoozeCount: 2,
                createdAt: at(day(offset: -1), 8)
            ),
            TaskItem(
                title: "Buy shampoo",
                importance: .low,
                timing: .unscheduled,
                createdAt: at(day(offset: -3), 17, 45)
            ),
            TaskItem(
                title: "Send the paperwork",
                details: "Scan both pages before sending.",
                importance: .high,
                timing: .dueBy(at(day(offset: 2), 12)),
                deadline: at(day(offset: 2), 12),
                createdAt: at(day(offset: -1), 21, 15)
            ),
            TaskItem(
                title: "Send the invoice",
                status: .completed,
                importance: .normal,
                timing: .dueBy(at(day(offset: -1), 17)),
                createdAt: at(day(offset: -3), 11),
                completedAt: at(day(offset: -1), 16, 22)
            ),
        ]

        // MARK: Memory

        let gettingReady = MemoryItem(
            kind: .routine,
            content: "You usually need around 45 minutes to get ready for work.",
            salience: 0.9,
            tags: ["morning", "work"],
            createdAt: at(day(offset: -12), 9),
            source: .assistant
        )

        let memories: [MemoryItem] = [
            gettingReady,
            MemoryItem(
                kind: .routine,
                content: "You leave about 30 minutes before a shift starts.",
                salience: 0.8,
                tags: ["work", "travel"],
                createdAt: at(day(offset: -9), 15, 20),
                source: .observation
            ),
            MemoryItem(
                kind: .preference,
                content: "Important reminders should repeat until you confirm you've done them.",
                salience: 0.95,
                tags: ["reminders"],
                createdAt: at(day(offset: -20), 22, 40),
                source: .user
            ),
            MemoryItem(
                kind: .preference,
                content: "You'd rather not hear anything before 8 AM unless it's urgent.",
                salience: 0.7,
                tags: ["quiet hours"],
                createdAt: at(day(offset: -18), 8, 5),
                source: .user
            ),
            MemoryItem(
                kind: .person,
                content: "Anna — girlfriend. Her birthday is on the 20th.",
                salience: 0.85,
                tags: ["people"],
                createdAt: at(day(offset: -30), 19),
                source: .user
            ),
            MemoryItem(
                kind: .recurringCommitment,
                content: "Rent is due on the 1st of every month.",
                salience: 0.9,
                tags: ["money"],
                createdAt: at(day(offset: -25), 12),
                source: .user
            ),
            MemoryItem(
                kind: .place,
                content: "Work is about 30 minutes away by bus.",
                salience: 0.6,
                tags: ["places", "work"],
                createdAt: at(day(offset: -14), 7, 30),
                source: .assistant
            ),
            MemoryItem(
                kind: .fact,
                content: "You stop drinking coffee after 3 PM so you can sleep.",
                salience: 0.5,
                tags: ["health"],
                createdAt: at(day(offset: -7), 15, 10),
                source: .observation
            ),
        ]

        // MARK: Reminder plans, generated by the real planner

        let planner = DefaultSupportPlanner()
        let planningContext = SupportPlanningContext(
            profile: profile,
            preferences: settings.support,
            now: now,
            calendar: calendar
        )

        func plan(for event: CalendarItem) -> ReminderPlan {
            planner.makePlan(
                for: ReminderSubject(
                    reference: .calendarItem(event.id),
                    title: event.title,
                    anchor: .moment(event.start),
                    importance: event.importance,
                    preparationDuration: event.preparationDuration,
                    travelDuration: event.travelDuration,
                    isTimeFixed: true
                ),
                context: planningContext
            )
        }

        let workPlan = plan(for: workEvent)
        let haircutPlan = plan(for: haircutEvent)

        let billPlan = planner.makePlan(
            for: ReminderSubject(
                reference: .task(billTask.id),
                title: billTask.title,
                anchor: .deadline(at(today, 21)),
                importance: .high,
                isTimeFixed: false
            ),
            context: planningContext
        )

        // Link the plan back to the task it supports.
        if let index = tasks.firstIndex(where: { $0.id == billTask.id }) {
            tasks[index].reminderPlanID = billPlan.id
        }

        return DemoData(
            profile: profile,
            settings: settings,
            events: [workEvent, haircutEvent, dentistEvent],
            tasks: tasks,
            memories: memories,
            reminderPlans: [workPlan, haircutPlan, billPlan],
            haircutEventID: haircutEvent.id,
            gettingReadyMemoryID: gettingReady.id
        )
    }

    /// Quick prompts offered when the conversation is short.
    static let suggestedPrompts = [
        "What's happening today?",
        "Remind me about something",
        "Add an appointment",
        "I need to get something done",
    ]
}
